# alembic/script.py.mako
# Alembic migration template
"""add_negotiation_flexibility

Revision ID: a5370d2ea086
Revises: 0001
Create Date: 2026-07-11 20:42:41.631178

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5370d2ea086'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_vendor_id'), 'bookings', ['vendor_id'], unique=False)
    op.drop_index(op.f('ix_allocations_event_id'), table_name='event_vendor_allocations')
    op.create_index(op.f('ix_event_vendor_allocations_event_id'), 'event_vendor_allocations', ['event_id'], unique=False)
    op.add_column('events', sa.Column('negotiation_flexibility', sa.Numeric(precision=3, scale=2), server_default='0.15', nullable=False))
    op.create_check_constraint(
        'check_negotiation_flexibility',
        'events',
        'negotiation_flexibility >= 0.0 AND negotiation_flexibility <= 0.30'
    )
    op.alter_column('events', 'analyzer_reasoning',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('events_firestore_id_key'), 'events', type_='unique')
    op.drop_index(op.f('ix_events_firestore_id'), table_name='events')
    op.create_index(op.f('ix_events_firestore_id'), 'events', ['firestore_id'], unique=True)
    op.drop_column('events', 'negotiation_margin')
    op.alter_column('llm_usage_log', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_llm_log_created_at'), table_name='llm_usage_log')
    op.drop_index(op.f('ix_llm_log_event_id'), table_name='llm_usage_log')
    op.create_index(op.f('ix_llm_usage_log_event_id'), 'llm_usage_log', ['event_id'], unique=False)
    op.drop_constraint(op.f('negotiations_firestore_id_key'), 'negotiations', type_='unique')
    op.drop_index(op.f('ix_negotiations_firestore_id'), table_name='negotiations')
    op.create_index(op.f('ix_negotiations_firestore_id'), 'negotiations', ['firestore_id'], unique=True)
    op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_constraint(op.f('vendors_firebase_uid_key'), 'vendors', type_='unique')
    op.drop_index(op.f('ix_vendors_firebase_uid'), table_name='vendors')
    op.create_index(op.f('ix_vendors_firebase_uid'), 'vendors', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_firebase_uid'), table_name='vendors')
    op.create_index(op.f('ix_vendors_firebase_uid'), 'vendors', ['firebase_uid'], unique=False)
    op.create_unique_constraint(op.f('vendors_firebase_uid_key'), 'vendors', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_negotiations_firestore_id'), table_name='negotiations')
    op.create_index(op.f('ix_negotiations_firestore_id'), 'negotiations', ['firestore_id'], unique=False)
    op.create_unique_constraint(op.f('negotiations_firestore_id_key'), 'negotiations', ['firestore_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_llm_usage_log_event_id'), table_name='llm_usage_log')
    op.create_index(op.f('ix_llm_log_event_id'), 'llm_usage_log', ['event_id'], unique=False)
    op.create_index(op.f('ix_llm_log_created_at'), 'llm_usage_log', ['created_at'], unique=False)
    op.alter_column('llm_usage_log', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('events', sa.Column('negotiation_margin', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_firestore_id'), table_name='events')
    op.create_index(op.f('ix_events_firestore_id'), 'events', ['firestore_id'], unique=False)
    op.create_unique_constraint(op.f('events_firestore_id_key'), 'events', ['firestore_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('events', 'analyzer_reasoning',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('check_negotiation_flexibility', 'events', type_='check')
    op.drop_column('events', 'negotiation_flexibility')
    op.drop_index(op.f('ix_event_vendor_allocations_event_id'), table_name='event_vendor_allocations')
    op.create_index(op.f('ix_allocations_event_id'), 'event_vendor_allocations', ['event_id'], unique=False)
    op.drop_index(op.f('ix_bookings_vendor_id'), table_name='bookings')
    # ### end Alembic commands ###
