# alembic/script.py.mako
# Alembic migration template
"""add_floor_price

Revision ID: e47b9bbd0e74
Revises: a5370d2ea086
Create Date: 2026-07-11 21:03:37.330637

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47b9bbd0e74'
down_revision: Union[str, None] = 'a5370d2ea086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiations', sa.Column('floor_price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negotiations', 'floor_price')
    # ### end Alembic commands ###
